pipeline {
    agent any
    tools{
        gradle 'gradle 7.0.2'
    }
    stages {
        stage('Build') {
            steps {
                sh 'gradle assemble'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Build Docker image') {
            steps {
                sh 'docker build -t javatechie/devops-integration .'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh 'gradle dockerRun'
            }
        }
    }
}
